name: Release Creation
on: 
  push:
    branches:
      - master
jobs:
  release-tag:
    name: Create Release Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@v1
        with: 
          tag_name: v0.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 