name: Unit Tests
on: pull_request
jobs:
  terraform-linting-terratesting:
    name: Linting and Testing
    runs-on: ubuntu-latest
    services: 
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: ec2,dynamodb,s3
          DEFAULT_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: localkey
          AWS_SECRET_ACCESS_KEY: localsecret
        ports:
          - 4566:4566
          - 4571:4571
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses:  hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5
          terraform_wrapper: false
      - uses: FranzDiebold/github-env-vars-action@v2  
      - name: Create AWS Bucket
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 mb --endpoint-url=http://0.0.0.0:4566 s3://eks-module-terraform-tfstate
        env:
          DEFAULT_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: localkey
          AWS_SECRET_ACCESS_KEY: localsecret
          AWS_ACCOUNT_ID: "000000000000"
      - name: Create Dynamodb Table
        uses: ItsKarma/aws-cli@v1.70.0
        with: 
          args: dynamodb --endpoint-url=http://0.0.0.0:4566 create-table --table-name terraform-state-lock --attribute-definitions AttributeName=LockID,AttributeType=S --key-schema AttributeName=LockID,KeyType=HASH --provisioned-throughput ReadCapacityUnits=10,WriteCapacityUnits=5
        env:
          DEFAULT_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: localkey
          AWS_SECRET_ACCESS_KEY: localsecret
          AWS_ACCOUNT_ID: "000000000000"
      - name: Download Go Modules
        run: go mod download
      - name: Terraform Linting
        run: terraform fmt -recursive -check
      - name: Go Linting 
        working-directory: test
        run: go fmt
      - name: Run Go Tests
        id: terratest
        working-directory: test
        run: | 
          go test -test.timeout 0 -v -identifier $CI_SHA_SHORT 
        env:
          AWS_ACCESS_KEY_ID: noroute
          AWS_SECRET_ACCESS_KEY: noroute
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          job_name: Terratesting VPC Module
          fields: repo,message,commit,author,ref,workflow 
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
