name: Unit Tests

on: push

jobs:
  # terraform-linting:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v2
  #     - name: Terraform linting
  #       uses: hashicorp/setup-terraform@v1
  #       with:
  #         terraform_version: 0.13.5
  #         terraform_wrapper: false
  #       run: terraform fmt -recursive -check

  golang-linting:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Run Golang Linting
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        working-directory: test
        run: go fmt

  golang-terratesting:
    env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: git env vars
        uses: FranzDiebold/github-env-vars-action@v2 
      - name: checkout terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5
          terraform_wrapper: false
      - name: Run Golang Linting
        uses: actions/setup-go@v1
        with:
          go-version: 1.13     
        working-directory: test
        run: |
         go mod download
         test -test.timeout 0 -v -identifier $CI_SHA_SHORT 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: send slack message
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          job_name: Terratesting VPC Module
          fields: repo,message,commit,author,ref,workflow,job 
        if: always()

          
